### ISSUE TITLE
main.js still being generated for Less files

### ISSUE THREAD

**Issue by hugomn** [jsilvax/webpack-omit-js-for-css-plugin#1]
Hello! Maybe I didn't get exactly how to make this plugin work, but I have a webpack config that receive a `index.less` file and generates a `index.css` along with a `index.js` (not needed) file. Is this plugin supposed to work in this case? If not, is a PR welcome or is subject for another plugin? Thanks!

**Comment by jsilvax** [comment]
.less, .scss, .sass files are currently not supported in this project. However, it probably is a good idea to include support. I'll look into it this week.

**Comment by hugomn** [comment]
Is it opened for a PR? I can make it today.

**Comment by jsilvax** [comment]
Yeah PR's are welcome. Please included the unit tests associated with the updates.

**Comment by hugomn** [comment]
Will do it. Thanks!

**Comment by hugomn** [comment]
Oh, awesome! Will test in a few. Thank you so much!
